### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by ekaj2** [TheDuckCow/blenderAddonReloading#1]
Not sure if this is the one you were referring to in your readme, but this is the one I built: https://gitlab.com/integrity-sg/zip_addon_reloader

I'm currently in the process of getting it to work in Blender 3. Who knows I might find out now that it isn't needed anymore lol

**Comment by TheDuckCow** [comment]
Hey! I should probably archive this repo as I never really did anything with it. In general for blender addon work, I've shifted to python or bash scripts to perform this work based on specific project needs. See MCprep as one example (and where it referenced the compile and test scripts)https://github.com/TheDuckCow/MCprep/blob/master/CONTRIBUTING.mdI want to say I saw someone make an actual addon that you could point to folders and have it do the zip work, and worked in a semi general way. I never used though as each project I find ends up with bespoke custom needs, so I keep forming a similar variant of a command line builder script. Nonetheless - good luck!On Aug 8, 2022 2:40 PM, Jake Dube ***@***.***> wrote:
Not sure if this is the one you were referring to in your readme, but this is the one I built: https://gitlab.com/integrity-sg/zip_addon_reloader
I'm currently in the process of getting it to work in Blender 3. Who knows I might find out now that it isn't needed anymore lol
